Assignment3:Cashier Barista FileHandler main
	g++ Cashier.o Barista.o FileHandler.o main.o -o Assignment3
Cashier:
	g++ -std=c++11 -c Cashier.cpp -o Cashier.o
Barista:
	g++ -std=c++11 -c Barista.cpp -o Barista.o
FileHandler:
	g++ -std=c++11 -c FileHandler.cpp -o FileHandler.o
main:
	g++ -std=c++11 -c main.cpp -o main.o
	
	

